version: 0.1.{build}-{branch}

environment:

  matrix:

    - PYTHON_VERSION: 3.6
      PYTHON_ARCH: x64
      MINICONDA: C:\Miniconda36-x64

    - PYTHON_VERSION: 3.7
      PYTHON_ARCH: x64
      MINICONDA: C:\Miniconda36-x64

    - PYTHON_VERSION: 3.5
      PYTHON_ARCH: x64
      MINICONDA: C:\Miniconda36-x64

matrix:

  allow_failures:

    - PYTHON_VERSION: 3.7
      PYTHON_ARCH: x64
      MINICONDA: C:\Miniconda36-x64

    - PYTHON_VERSION: 3.5
      PYTHON_ARCH: x64
      MINICONDA: C:\Miniconda36-x64

install:
  - set PATH=%MINICONDA%;%MINICONDA%\Scripts;%PATH%

  # Install the build and runtime dependencies of the project.
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --add channels conda-forge
  - conda create -q -n test-environment python=%PYTHON_VERSION%
  - activate test-environment
  - pip install wheel

  # Check that we have the expected version of Python
  - python --version

  - pip install coveralls PyYAML
  - pip install PySide2
  - conda install numpy matplotlib-base gdal pyproj scipy basemap netCDF4 h5py lxml pillow
  - pip install https://github.com/hydroffice/hyo2_abc/archive/master.zip
  - pip install pytest pytest-cov

build: off
build_script:
  - pip install .
  # - conda remove --force PyQt Qt sip
  - del /q %MINICONDA%\envs\test-environment\qt.conf
  - conda list --show-channel-urls
  # The following two rows download from FTP files that may be required for running the test suite
  # - python data/download_products.py
  # - python data/download_raw_km.py
  - python data/download_raw_reson.py
  - python data/download_auxiliaries.py

test: off
test_script:
  - py.test --cov=hyo2.openbst
  - coveralls

after_test:
  - python setup.py bdist_wheel

artifacts:
  - path: dist\*
